baseURL = 'https://otterable2.github.io'
languageCode = 'en-us'
title = 'Ermine.eu - The Otter Principles'
theme = 'maverick'

# Main Menu
[menu]
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 1
	
  [[menu.main]]
    identifier = "Author site"
    name = "> Author site"
    url = "https://ermine.de"
    weight = 3